#ifndef _INCLUDE_YCGAMESTAGEDEFINE_H_
#define _INCLUDE_YCGAMESTAGEDEFINE_H_

#define TRANSFER_LUA		1
#define TRANSFER_NETWORK	2
#define TRANSFER_GRAPHIC	3
#define TRANSFER_UI			4
#define TRANSFER_IP			5
#define TRANSFER_PORT		6
#define TRANSFER_SESSION	7
#define TRANSFER_ROLEID		8

#endif